### PR TITLE
Enable compilation under windows

### PR DESCRIPTION
**Pull request by yakobowski**
.so files have a .dll extension under Win32

### CODE REVIEW

**Comment by yakobowski** [comment]
BTW, thanks for making profiling optional, this was the other reason why compilation under Windows was failing.

**Comment by nberth** [comment]
Thanks for bringing this change.

Although, my `ocamlc -config` shows me an `ext_dll` entry that may be more suitable. I think it would be more appropriate to use it instead; and OCaml 3.12.1 seems to show it too.

**Comment by yakobowski** [comment]
Much better indeed. I will update the PR.

**Comment by nberth** [comment]
Thanks for the change. I'll accept it and amend slightly later as I don't like the `rm -f … *$(EXT_DLL)` with `EXT_DLL` coming from a configuration file.

**Comment by yakobowski** [comment]
Makes sense indeed.

Do you mind doing a new release with this change? This way I will be able to submit a PR to the windows opam repo.

(BTW: the opam files in the repo are still using Opam 1.2 syntax, but I think all opam repos have now switched.)

**Comment by nberth** [comment]
Sure I'll make a release now.

(Yes opam files are still in 1.2 format: that's on purpose as I also maintain a custom—academic—OPAM repository whom I don't want to force the users to upgrade to 2.0 — `opam admin` provides nice facilities to publish to the new format anyways.)

**Pull request merged**
